# Generated by Django 4.1.6 on 2023-07-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
